spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:hsqldb:file:gtagged.db

gtagged:
  storage:
    directory: storage

logging:
  level:
    org.springframework.security: TRACE
